### ISSUE TITLE
Inline comments kills all the CSS following it

### ISSUE THREAD

**Issue by toastedcornflakes** [sprymix/csscompressor#2]
If my css file contains something like

```
body { 
    font-size:1em;
}
// my stuff
nav { 
    font-size:1.5em;
}
```

Then the minifying will remove the line return before `nav`, and comment out the rest of the CSS.

**Comment by 1st1** [comment]
There are no `//` comments in the CSS spec: https://developer.mozilla.org/en-US/docs/Web/CSS/Comments

**Comment by toastedcornflakes** [comment]
Woops, sorry for wasting your time
