### ISSUE TITLE
Are there plans to add tests for python 3.4 and 3.5?

### ISSUE THREAD

**Issue by nueverest** [sprymix/csscompressor#7]
It would be nice to see 3.4 and 3.5 covered. I like how fast it is.

**Comment by meshy** [comment]
[As far as I can tell](https://github.com/sprymix/csscompressor/blob/master/.travis.yml#L10-L11), they're [already in the test suite](https://travis-ci.org/sprymix/csscompressor/jobs/97233813).

**Comment by 1st1** [comment]
Right. README probably needs an update ;)
